-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--
-- Cursor
-- vim.o.guicursor =
--   "n-v-c:block,i:block-Cursor/blinkwait40-blinkon20-blinkoff40,r:block,o:block,a:block,sm:block,v:block,ve:block"
--
--
-- Set the default scrolloff values
-- vim.opt.scrolloff = 999
-- vim.opt.sidescrolloff = 8
