-- return {
--   "nvim-treesitter/nvim-treesitter",
--   opts = function(_, opts)
--     -- add tsx and treesitter
--     vim.list_extend(opts.ensure_installed, {
--       "tsx",
--       "prisma",
--       "rust",
--       "typescript",
--     })
--   end,
-- }
--
--
return { import = "lazyvim.plugins.extras.lang.typescript" }
